CREATE DATABASE QL_HOCVIEN
USE QL_HOCVIEN
go
CREATE TABLE BIEN_LAI
(
	MaBL INT NOT NULL UNIQUE,
	NgayBL DATE NOT NULL,
	NoiDung NVARCHAR(100) NOT NULL,
	SoTien INT NOT NULL,
	BangChu NVARCHAR(500) NOT NULL,
	CONSTRAINT PK_BIEN_LAI PRIMARY KEY (MaBL),
	CONSTRAINT CHK_NGAYBL CHECK (NgayBL > GETDATE() - 1)
)

CREATE TABLE CA_HOC
(
	MaCaHoc INT NOT NULL UNIQUE,
	Buoi NCHAR(10),
	Gio VARCHAR(15),
	CONSTRAINT PK_CA_HOC PRIMARY KEY (MaCaHoc)
)

CREATE TABLE DIEN_GIAM_PHI
(
	MaDien CHAR(7) NOT NULL UNIQUE,
	TenDien NVARCHAR(50) NOT NULL,
	MucGiam INT,
	CONSTRAINT PK_DIEN_GIAM_PHI PRIMARY KEY (MaDien)
)

CREATE TABLE GIAO_VIEN
(
	MaGiaoVien CHAR(7) NOT NULL UNIQUE,
	HoGiaoVien NVARCHAR(50) NOT NULL,
	TenGiaoVien NVARCHAR(10) NOT NULL,
	NgaySinh DATE,
	DiaChi NVARCHAR(100),
	CONSTRAINT PK_GIAO_VIEN PRIMARY KEY (MaGiaoVien)
)

CREATE TABLE HOC_VIEN
(
	MaHocVien CHAR(7) NOT NULL UNIQUE,
	HoHocVien NVARCHAR(50) NOT NULL,
	TenHocVien NVARCHAR(10) NOT NULL,
	NgaySinh DATE NOT NULL,
	DiaChi NVARCHAR(100) NOT NULL,
	SoDT CHAR(11),
	NgheNghiep NVARCHAR(50),
	CONSTRAINT PK_HOC_VIEN PRIMARY KEY (MaHocVien)
)
SET DATEFORMAT dmy
insert into HOC_VIEN values 
('200',N'Võ',N'QUANG','26/04/1997',N'Đà Nẵng','0964618414',N'Sinh viên'),
('201',N'Võ DUY',N'QUANG','26/04/1997',N'Đà Nẵng','0125451494',N'Sinh viên'),
('202',N' Nguyễn Huyền ',N'Trang','26/06/1997',N'Đà Nẵng','0163452145',N'Sinh viên'),
('203',N'Trần Thị',N'Tuyết ','12/12/1997',N'Đà Nẵng','0164751122',N'Sinh viên'),
('204',N'Nguyễn Hồng',N'Thuận','24/02/1997',N'Đà Nẵng','0154578974',N'Sinh viên'),
('205',N'Dương Đình',N'Chiến','10/04/1997',N'Đà Nẵng','0165235987',N'Sinh viên'),
('206',N'Trần Quang',N'Thoại','25/04/1996',N'Đà Nẵng','0165456789',N'Sinh viên'),
('207',N'Dương Thị',N'Chiến','26/05/1994',N'Đà Nẵng','0165618414',N'Sinh viên'),
('208',N'Trần Đình',N'QUANG','1/03/1997',N'Đà Nẵng','0964466154',N'Sinh viên')
select  *
from HOC_VIEN
CREATE TABLE KHOA_HOC
(
	MaKhoaHoc CHAR(7) NOT NULL ,
	TenKhoaHoc NVARCHAR(100) NOT NULL,
	NgayBD DATE NOT NULL,
	NgayKT DATE NOT NULL,
	CONSTRAINT PK_KHOA_HOC PRIMARY KEY (MaKhoaHoc),
	CONSTRAINT CHK_NGAYBD_KHOAHOC CHECK (NgayBD > GETDATE() - 1),
	CONSTRAINT CHK_NGAYKT_KHOAHOC CHECK (NgayKT > GETDATE() - 1),
	CONSTRAINT CHK_NGAYBD_NGAYKT_KHOAHOC CHECK (NgayBD <= NgayKT)
)

CREATE TABLE KY_THI
(
	MaKyThi CHAR(7) NOT NULL UNIQUE,
	TenKyThi NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_KY_THI PRIMARY KEY (MaKyThi)
)

CREATE TABLE LOAI_PHONG
(
	MaLoaiPhong CHAR(3) NOT NULL UNIQUE,
	TenLoaiPhong NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_LOAI_PHONG PRIMARY KEY (MaLoaiPhong)
)

CREATE TABLE MON_HOC
(
	MaMonHoc CHAR(7) NOT NULL,
	MaKhoaHoc CHAR(7) NOT NULL,
	TenMonHoc NVARCHAR(50) NOT NULL,
	HocPhi INT NOT NULL,
	CONSTRAINT PK_MON_HOC PRIMARY KEY (MaMonHoc),
	CONSTRAINT FK_MON_HOC_KHOA_HOC FOREIGN KEY (MaKhoaHoc) REFERENCES KHOA_HOC
)

ALTER TABLE MON_HOC ADD PRIMARY KEY(TenMonHoc)
CREATE TABLE LOP_HOC
(
	MaLopHoc CHAR(7) NOT NULL,
	MaMonHoc CHAR(7) NOT NULL,
	SiSoDK INT NOT NULL,
	NgayBD DATE NOT NULL,
	NgayKT DATE NOT NULL,
	DaKhoa INT NOT NULL, -- the value of 0 or 1, description as boolean type
	CONSTRAINT PK_LOP_HOC PRIMARY KEY (MaLopHoc),
	CONSTRAINT FK_LOP_HOC_MON_HOC FOREIGN KEY (MaMonHoc) REFERENCES MON_HOC,
	CONSTRAINT CHK_NGAYBD_LOPHOC CHECK (NgayBD > GETDATE() - 1),
	CONSTRAINT CHK_NGAYKT_LOPHOC CHECK (NgayKT > GETDATE() - 1),
	CONSTRAINT CHK_NGAYBD_NGAYKT_LOPHOC CHECK (NgayBD <= NgayKT)
)

CREATE TABLE PHONG_HOC
(
	MaPhong CHAR(3) NOT NULL UNIQUE,
	TenPhong NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_PHONG_HOC PRIMARY KEY (MaPhong)
)

CREATE TABLE DANG_KY
(
	MaLopHoc CHAR(7) NOT NULL,
	MaBL INT NOT NULL,
	CONSTRAINT PK_DANG_KY PRIMARY KEY (MaLopHoc, MaBL),
	CONSTRAINT FK_DANG_KY_LOP_HOC FOREIGN KEY (MaLopHoc) REFERENCES LOP_HOC,
	CONSTRAINT FK_DANG_KY_BIEN_LAI FOREIGN KEY (MaBL) REFERENCES BIEN_LAI
)

CREATE TABLE GIAM_PHI
(
	MaHocVien CHAR(7) NOT NULL,
	MaDien CHAR(7) NOT NULL,
	CONSTRAINT PK_GIAM_PHI PRIMARY KEY (MaHocVien, MaDien),
	CONSTRAINT FK_GIAM_PHI_HOC_VIEN FOREIGN KEY (MaHocVien) REFERENCES HOC_VIEN,
	CONSTRAINT FK_GIAM_PHI_DIEN_GIAM_PHI FOREIGN KEY (MaDien) REFERENCES DIEN_GIAM_PHI
)

CREATE TABLE DAY
(
	MaMonHoc CHAR(7) NOT NULL,
	MaGiaoVien CHAR(7) NOT NULL,
	CONSTRAINT PK_DAY PRIMARY KEY (MaMonHoc, MaGiaoVien),
	CONSTRAINT FK_DAY_MON_HOC FOREIGN KEY (MaMonHoc) REFERENCES MON_HOC,
	CONSTRAINT FK_DAY_GIAO_VIEN FOREIGN KEY (MaGiaoVien) REFERENCES GIAO_VIEN
)

CREATE TABLE PHAN_CONG
(
	MaGiaoVien CHAR(7) NOT NULL,
	MaCaHoc INT NOT NULL,
	MaLopHoc CHAR(7) NOT NULL,
	CONSTRAINT PK_PHAN_CONG PRIMARY KEY (MaGiaoVien, MaCaHoc, MaLopHoc),
	CONSTRAINT FK_PHAN_CONG_GIAO_VIEN FOREIGN KEY (MaGiaoVien) REFERENCES GIAO_VIEN,
	CONSTRAINT FK_PHAN_CONG_CA_HOC FOREIGN KEY (MaCaHoc) REFERENCES CA_HOC,
	CONSTRAINT FK_PHAN_CONG_LOP_HOC FOREIGN KEY (MaLopHoc) REFERENCES LOP_HOC
)
CREATE TABLE XEPLICHTHI
(
MaKhoaHoc CHAR(7) NOT NULL,
MaMonHoc CHAR(7) NOT NULL,
TenMonHoc NVARCHAR(50) NOT NULL,
NGTHI datetime not null,
GIOTHI datetime NOT NULL,
DIADIEM NVARCHAR(200) NOT NULL,
GHICHU NVARCHAR(500),




)
ALTER TABLE XEPLICHTHI
ADD CONSTRAINT PK_MAMON PRIMARY KEY (MaMonHoc)
ALTER TABLE XEPLICHTHI
ADD CONSTRAINT FK_MAMONHOC  FOREIGN KEY (MaMonHoc) REFERENCES MON_HOC
ALTER TABLE XEPLICHTHI
ADD CONSTRAINT FK_MAKHOAHOC FOREIGN KEY (MaKhoaHoc) references KHOA_HOC

alter table XEPLICHTHI DROP CHK_NGTHI
alter table XEPLICHTHI DROP PK_MAMON
alter table XEPLICHTHI DROP PK
ALTER TABLE XEPLICHTHI DROP FK_MAMONHOC



select *
FROM XEPLICHTHI
update XEPLICHTHI set GHICHU=N'Không được dùng máy tính' where MaKhoaHoc='09DHTH'
delete from XEPLICHTHI where MaMonHoc='MH004'
ALTER TABLE MON_HOC
ADD CONSTRAINT FK_MON FOREIGN KEY (TenMonHoc) REFERENCES MON_HOC(TenMonHoc)
/*
CREATE TABLE THI
(
	MaKyThi CHAR(7) NOT NULL,
	MaHocVien CHAR(7) NOT NULL,
	MaPhong CHAR(3) NOT NULL,
	NgayThi DATE,
	KetQua FLOAT,
	XepLoai NVARCHAR,
	CONSTRAINT PK_THI PRIMARY KEY (MaKyThi, MaHocVien, MaPhong),
	CONSTRAINT FK_THI_KY_THI FOREIGN KEY (MaKyThi) REFERENCES KY_THI,
	CONSTRAINT FK_THI_HOC_VIEN FOREIGN KEY (MaHocVien) REFERENCES HOC_VIEN,
	CONSTRAINT FK_THI_PHONG FOREIGN KEY (MaPhong) REFERENCES PHONG_HOC,
	CONSTRAINT CHK_NGAYTHI CHECK (NgayThi > GETDATE() - 1)
)
*/
CREATE TABLE TINH_TRANG_PHONG
(
	MaLopHoc CHAR(7) NOT NULL, 
	MaCaHoc INT NOT NULL,
	MaPhong CHAR(3) NOT NULL,
	CONSTRAINT PK_TINH_TRANG_PHONG PRIMARY KEY (MaLopHoc, MaCaHoc, MaPhong),
	CONSTRAINT FK_TINH_TRANG_PHONG_LOP_HOC FOREIGN KEY (MaLopHoc) REFERENCES LOP_HOC,
	CONSTRAINT FK_TINH_TRANG_PHONG_CA_HOC FOREIGN KEY (MaCaHoc) REFERENCES CA_HOC,
	CONSTRAINT FK_TINH_TRANG_PHONG_PHONG_HOC FOREIGN KEY (MaPhong) REFERENCES PHONG_HOC
)

CREATE TABLE XUAT
(
	MaBL INT NOT NULL,
	MaHocVien CHAR(7) NOT NULL,
	CONSTRAINT PK_XUAT PRIMARY KEY (MaBL, MaHocVien),
	CONSTRAINT FK_XUAT_BIEN_LAI FOREIGN KEY (MaBL) REFERENCES BIEN_LAI,
	CONSTRAINT FK_XUAT_HOC_VIEN FOREIGN KEY (MaHocVien) REFERENCES HOC_VIEN
)

--ALTER TABLE LOP_HOC ADD CONSTRAINT CHK_NGAYBD_LOPHOC_KHOAHOC CHECK (LOP_HOC.NgayBD >= KHOA_HOC.NgayBD);
--ALTER TABLE LOP_HOC ADD CONSTRAINT CHK_NGAYKT_LOPHOC_KHOAHOC CHECK (LOP_HOC.NgayKT <= KHOA_HOC.NgayKT);

SET DATEFORMAT dmy;
INSERT INTO KHOA_HOC VALUES
('06DHTH', '06', '1/11/2017', '30/10/2018'),
('07DHTH', '07', '1/11/2018', '30/10/2019'),
('08DHTH', '08', '1/11/2018', '10/11/2019'),
('09DHTH', '09', '1/11/2018', '20/12/2019')

select *
from KHOA_HOC
INSERT INTO MON_HOC VALUES
('MH001', '06DHTH', N'Tin học văn phòng',1200000),
('MH002', '07DHTH', N'Đồ họa máy tính', 800000),
('MH003', '08DHTH', N'Kỹ thuật lập trình', 1100000),
('MH004', '09DHTH', N'Lập trình hướng đối tượng',1180000)

insert into MON_HOC values
('MH005', '09DHTH', N'Lập trình hướng đối tượng',1180000)
SELECT * FROM MON_HOC


Select * From LOP_HOC

SELECT * FROM MON_HOC


INSERT INTO LOP_HOC VALUES
('06DHTH1', 'MH001', 0, '2/11/2017', '2/12/2017', 0),
('06DHTH2', 'MH002', 0, '2/11/2017', '2/12/2017', 0),
('05DHTH3', 'MH003', 0, '2/11/2017', '2/12/2017', 0),
('05DHTH4', 'MH004', 0, '2/11/2017', '2/12/2017', 0)

SELECT * FROM LOP_HOC

INSERT INTO CA_HOC VALUES
('1', N'Sáng', '7h15'),
('2', N'Sáng', '9h30'),
('3', N'Chiều', '13h15'),
('4', N'Chiều', '3h15')

SELECT * FROM CA_HOC

SELECT * FROM BIEN_LAI
SELECT * FROM DIEN_GIAM_PHI
SELECT * FROM HOC_VIEN
SELECT * FROM DANG_KY
SELECT * FROM GIAM_PHI
SELECT * FROM XUAT







create table CHUONGTRINH
(
STT INT NOT NULL,
NGAYDANG date not null,
LOAIDAOTAO NVARCHAR(100),
NOIDUNG NVARCHAR(1000) NOT  NULL,
PRIMARY KEY (STT)


)
delete from CHUONGTRINH
create table QUANLYTAIKHOAN
(
Username nvarchar(50) not null,
PASSWORD varchar(50) NOT NULL, 
Chucvu nvarchar(50),
constraint pk_MK primary key (Username) 



)
select STT,LOAIDAOTAO,NOIDUNG,CONVERT(CHAR,NGAYDANG,3) as NGAYDANG FROM CHUONGTRINH

insert into QUANLYTAIKHOAN values 
(N'voduyquang',123,N'Giáo viên'),
(N'leviethao',1234,N'Nhân viên'),
(N'trần tuấn nhanh',12345,N'Kế toán')



select *
fROM QUANLYTAIKHOAN
SET DATEFORMAT dmy
insert into CHUONGTRINH values 
(1,'10/10/2017',N'Chương trình đạo tạo quốc tế',N'Trao học bổng cho sinh viên chương trình liên kết quốc tế với Trường Đại học Mỹ Hòa (Đài Loan)'),
(2,'11/10/2017',N'Chương trình đạo tạo quốc tế',N'Thông tin tuyển sinh chương trình quốc tế ngành Công nghệ máy tính - Meiho Đài Loan '),
(3,'11/5/2017',N'Đào tạo ngắn hạn',N'THÔNG BÁO TỔ CHỨC THI THỬ TOEIC (LẦN THỨ 3)' ),
(4,'12/10/2017',N'Đào tạo ngắn hạn',N'Khai giảng các lớp luyện thi Chứng chỉ TOEIC quốc tế ')


select *
fROM CHUONGTRINH



update QUANLYTAIKHOAN set Username=N'Nguyễn thành',Chucvu=N'Nhân viên' where Username=N'kiều đại thiên' and Chucvu=N'văn phòng'


create table thoigian
(
NGAYTHI DATE NOT NULL,
GIOTHI TIME NOT NULL

)
SET DATEFORMAT dmy
insert into thoigian values
('30-10-2017','14:23:00'),
('30-10-2017','03:23')
insert into thoigian values
('30-10-2017','14:23:30')

insert into thoigian values
('30-10-2017','14:23:30')
select *
from thoigian
--select 
--ALTER TABLE LOP_HOC ADD CONSTRAINT CHK_NGAYBD_LOPHOC_KHOAHOC CHECK (LOP_HOC.NgayBD >= KHOA_HOC.NgayBD);
--ALTER TABLE LOP_HOC ADD CONSTRAINT CHK_NGAYKT_LOPHOC_KHOAHOC CHECK (LOP_HOC.NgayKT <= KHOA_HOC.NgayKT);
select GETDATE()




create table MSS
(
MaMonThi char(10) not null,
TenMonHoc NVARCHAR(50) NOT NULL,
MaPhongThi char(10) not null,
Masobd char(7) not null,
Masokt char(7) not null,
primary key(MaPhongThi,Masobd,Masokt)

)
alter table MSS
add constraint FK_MS foreign key (Masobd) references HOC_VIEN
alter table MSS
add constraint FK_MSKT foreign key (Masokt) references HOC_VIEN

select * 
from MSS
insert into MSS values
('201','205')
select *
from MSS
SELECT MS.Maso,Hoten,LopHoc
from MS,MSS
where    MS.Maso<=MSS.Masokt and  MS.Maso>=MSS.Masobd 